language: node_js

node_js:
- 8

cache:
  yarn: true
  directories:
  - node_modules

install:
- yarn

script:
- yarn lint
- yarn test -- --coverage
- yarn build

after_success:
- yarn dist
- ls -lha
- bash <(curl -s https://codecov.io/bash)

deploy:
# deploying to cdn.tutorcruncher.com/socket/
- provider: s3
  access_key_id:
    secure: "SKus8C48fdO72ch31uR2YKLAZFJRNRRbjQKJWG4xaAh7AOIvVQXXzBgqeDlY5vz4BreIHDOkMDF0/wSHF6Lm5wgNaelbu6VAn3ASupRybrpvEsD92HbDlcUAjjl8OCqaPAXnfwFMKQZ07g61nBOlQIvRGgJvgP0WLflWrB4kyjnyEbH2qIfRnfjYHMFP/xHpLrEr3fL+im2O4W12nTj5AMiS0FM/yb8NZrep8IK/c7jiQIceQuroPm5vTNdBC9ZiKSf0ggwCc2m/hmi+i8KX+OiHz8h8Q8T84J8aik7ig16CQsfXAZq+SUSIDTWIJ1VWY5L67aBaApZKZ1WNASFrREWAgLZvEEEqKUQCDqTE6nYn3Xmu8T1CQK23VObxAJMGs6KZ2DYB9Qsi15bgUK8TYZkKxTxeLLMWtPl9k3mD14NkkeE5TWOVlLr7ATURbzJCgaYkYhf5+4Pudhn8PnzFoJHEzcpEARP+GFAm6SFh8KXQvNiYqSGN2ui2gsb5m2PHjyxpbK2awGjs2EMxTuYHQcIfhEuT+qJ2G6fG9lcpe+/YLwky3E8BgAhMy/5Wzx03JMCwoc+K3/kMGiugGrNdfx5mofbG+lZVDTquPsHl2wzJorZ8Z1zhgWYJWt5LsgQD1u8FyBSOJDxtReaGN7B5qQ1wwNR+lVu3oNcfi3pOUMg="
  secret_access_key:
    secure: "ZsSpMvYPBlPHfMwrzT32iBM9CS2JPTazuz1PGiSpcXuISCwVOjoXaJKlDvUHa55rF67BdMRvu0nqMWKhhi9AnQkWKWIMnfBJ4T0qZ1eDfphLuT9YkJ/OerT03IHfY8VbxUuYLPJZ0p4Dh4BjZU5AlL5AzXUr82yMgrx+0sscAVY8yUvrtBxgrOKEoCCXd27rayOC6nLNQtpk8W4hd3gZ/4yRpK1ph0jrgb7MM57VoXYGOIE7ep4v3ejHl/8WLQoupAm8mTi4bwJzElGQTI6HLAACRDjSBjisKV0ZKoyxes6fvMV+jgeI+vwMUMzE8XTuXFnonnmNrxP9q55YFtrAENGBtenALGKMzf2VEKa1YFcXQbQZOpzIXJ8eGxTg2HLDreDr5cQ/T1sCZ4Ks9vGP6AYm//FgY8Q3Y7txqyTUNADtP9qvXTjc1HU1QVBAVeuW8YuuvrjElzAY2P5akObvPF3ks2J8J0oQ9BrVsB529d2KY8ym0ti5tLhe1Vu70yBKB7jfDPCXAIXIQ+2yOU9RrixE0NDHQcLCBFWB8/P9MhYXzGZuzTQM+BiLgSWM0pmlgRqFSg3VVa9GnbqQ7hIkTXTj4Gxi2pTU4VGHrr2BkL1yAdV36JXEx9BoGinB/H4NPcyW0gdsRElBpNn/4KJgGqzD48fa2hU7E5SvQGzUykg="
  bucket: cdn.tutorcruncher.com
  skip_cleanup: true
  acl: public_read
  region: eu-west-1
  local_dir: dist
  upload-dir: socket
  on:
    all_branches: true
